#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CommonCore_GoLive")]
	public partial class C8_Common_CoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_ReferenceType(tb_ReferenceType instance);
    partial void Updatetb_ReferenceType(tb_ReferenceType instance);
    partial void Deletetb_ReferenceType(tb_ReferenceType instance);
    partial void Inserttb_EmailTemplate(tb_EmailTemplate instance);
    partial void Updatetb_EmailTemplate(tb_EmailTemplate instance);
    partial void Deletetb_EmailTemplate(tb_EmailTemplate instance);
    #endregion
		
		public C8_Common_CoreDataContext() : 
				base(global::C8.Exchange.Services.Properties.Settings.Default.CommonCore_GoLiveConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public C8_Common_CoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public C8_Common_CoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public C8_Common_CoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public C8_Common_CoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_ReferenceType> tb_ReferenceTypes
		{
			get
			{
				return this.GetTable<tb_ReferenceType>();
			}
		}
		
		public System.Data.Linq.Table<tb_EmailTemplate> tb_EmailTemplates
		{
			get
			{
				return this.GetTable<tb_EmailTemplate>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_INSERT_EmailQueue")]
		public ISingleResult<pr_INSERT_EmailQueueResult> pr_INSERT_EmailQueue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationId", DbType="Int")] System.Nullable<int> applicationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAccountId", DbType="Int")] System.Nullable<int> emailAccountId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToList", DbType="VarChar(512)")] string toList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CcList", DbType="VarChar(512)")] string ccList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BccList", DbType="VarChar(512)")] string bccList, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subject", DbType="VarChar(1024)")] string subject, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Body", DbType="NVarChar(MAX)")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsHtml", DbType="Bit")] System.Nullable<bool> isHtml, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FailureCount", DbType="Int")] System.Nullable<int> failureCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceId", DbType="VarChar(32)")] string referenceId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceTypeId", DbType="Int")] System.Nullable<int> referenceTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasAttachments", DbType="Bit")] System.Nullable<bool> hasAttachments)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationId, emailAccountId, toList, ccList, bccList, subject, body, isHtml, failureCount, referenceId, referenceTypeId, hasAttachments);
			return ((ISingleResult<pr_INSERT_EmailQueueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SELECT_ApplicationByKey")]
		public ISingleResult<pr_SELECT_ApplicationByKeyResult> pr_SELECT_ApplicationByKey([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationKey", DbType="VarChar(50)")] string applicationKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationKey, isActive, isDeleted);
			return ((ISingleResult<pr_SELECT_ApplicationByKeyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SELECT_EmailAccount")]
		public ISingleResult<pr_SELECT_EmailAccountResult> pr_SELECT_EmailAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAccountId", DbType="Int")] System.Nullable<int> emailAccountId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emailAccountId, isActive, isDeleted);
			return ((ISingleResult<pr_SELECT_EmailAccountResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SELECT_EmailTemplates")]
		public ISingleResult<pr_SELECT_EmailTemplatesResult> pr_SELECT_EmailTemplates([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isActive, isDeleted);
			return ((ISingleResult<pr_SELECT_EmailTemplatesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_SELECT_EmailTemplatesByApplication")]
		public ISingleResult<pr_SELECT_EmailTemplatesByApplicationResult> pr_SELECT_EmailTemplatesByApplication([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationID", DbType="Int")] System.Nullable<int> applicationID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDeleted", DbType="Bit")] System.Nullable<bool> isDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationID, isActive, isDeleted);
			return ((ISingleResult<pr_SELECT_EmailTemplatesByApplicationResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_ReferenceTypes")]
	public partial class tb_ReferenceType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ReferenceTypeId;
		
		private string _ReferenceTypeName;
		
		private string _ReferenceTypeDescription;
		
		private string _ReferenceTypeKey;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
		private bool _IsLocked;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReferenceTypeIdChanging(int value);
    partial void OnReferenceTypeIdChanged();
    partial void OnReferenceTypeNameChanging(string value);
    partial void OnReferenceTypeNameChanged();
    partial void OnReferenceTypeDescriptionChanging(string value);
    partial void OnReferenceTypeDescriptionChanged();
    partial void OnReferenceTypeKeyChanging(string value);
    partial void OnReferenceTypeKeyChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    #endregion
		
		public tb_ReferenceType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceTypeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ReferenceTypeId
		{
			get
			{
				return this._ReferenceTypeId;
			}
			set
			{
				if ((this._ReferenceTypeId != value))
				{
					this.OnReferenceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ReferenceTypeId = value;
					this.SendPropertyChanged("ReferenceTypeId");
					this.OnReferenceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceTypeName", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string ReferenceTypeName
		{
			get
			{
				return this._ReferenceTypeName;
			}
			set
			{
				if ((this._ReferenceTypeName != value))
				{
					this.OnReferenceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._ReferenceTypeName = value;
					this.SendPropertyChanged("ReferenceTypeName");
					this.OnReferenceTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceTypeDescription", DbType="VarChar(1024)")]
		public string ReferenceTypeDescription
		{
			get
			{
				return this._ReferenceTypeDescription;
			}
			set
			{
				if ((this._ReferenceTypeDescription != value))
				{
					this.OnReferenceTypeDescriptionChanging(value);
					this.SendPropertyChanging();
					this._ReferenceTypeDescription = value;
					this.SendPropertyChanged("ReferenceTypeDescription");
					this.OnReferenceTypeDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceTypeKey", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string ReferenceTypeKey
		{
			get
			{
				return this._ReferenceTypeKey;
			}
			set
			{
				if ((this._ReferenceTypeKey != value))
				{
					this.OnReferenceTypeKeyChanging(value);
					this.SendPropertyChanging();
					this._ReferenceTypeKey = value;
					this.SendPropertyChanged("ReferenceTypeKey");
					this.OnReferenceTypeKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_EmailTemplates")]
	public partial class tb_EmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmailTemplateID;
		
		private int _ApplicationID;
		
		private string _EmailTemplateName;
		
		private string _EmailTemplateDescription;
		
		private string _EmailTemplateKey;
		
		private string _EmailFrom;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _Variables;
		
		private bool _IsHTML;
		
		private string _ToVariable;
		
		private string _CcVariable;
		
		private bool _HasVariables;
		
		private System.Nullable<bool> _SendAsOneEmail;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailTemplateIDChanging(int value);
    partial void OnEmailTemplateIDChanged();
    partial void OnApplicationIDChanging(int value);
    partial void OnApplicationIDChanged();
    partial void OnEmailTemplateNameChanging(string value);
    partial void OnEmailTemplateNameChanged();
    partial void OnEmailTemplateDescriptionChanging(string value);
    partial void OnEmailTemplateDescriptionChanged();
    partial void OnEmailTemplateKeyChanging(string value);
    partial void OnEmailTemplateKeyChanged();
    partial void OnEmailFromChanging(string value);
    partial void OnEmailFromChanged();
    partial void OnEmailSubjectChanging(string value);
    partial void OnEmailSubjectChanged();
    partial void OnEmailBodyChanging(string value);
    partial void OnEmailBodyChanged();
    partial void OnVariablesChanging(string value);
    partial void OnVariablesChanged();
    partial void OnIsHTMLChanging(bool value);
    partial void OnIsHTMLChanged();
    partial void OnToVariableChanging(string value);
    partial void OnToVariableChanged();
    partial void OnCcVariableChanging(string value);
    partial void OnCcVariableChanged();
    partial void OnHasVariablesChanging(bool value);
    partial void OnHasVariablesChanged();
    partial void OnSendAsOneEmailChanging(System.Nullable<bool> value);
    partial void OnSendAsOneEmailChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tb_EmailTemplate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmailTemplateID
		{
			get
			{
				return this._EmailTemplateID;
			}
			set
			{
				if ((this._EmailTemplateID != value))
				{
					this.OnEmailTemplateIDChanging(value);
					this.SendPropertyChanging();
					this._EmailTemplateID = value;
					this.SendPropertyChanged("EmailTemplateID");
					this.OnEmailTemplateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int NOT NULL")]
		public int ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this.OnApplicationIDChanging(value);
					this.SendPropertyChanging();
					this._ApplicationID = value;
					this.SendPropertyChanged("ApplicationID");
					this.OnApplicationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateName
		{
			get
			{
				return this._EmailTemplateName;
			}
			set
			{
				if ((this._EmailTemplateName != value))
				{
					this.OnEmailTemplateNameChanging(value);
					this.SendPropertyChanging();
					this._EmailTemplateName = value;
					this.SendPropertyChanged("EmailTemplateName");
					this.OnEmailTemplateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateDescription", DbType="VarChar(50)")]
		public string EmailTemplateDescription
		{
			get
			{
				return this._EmailTemplateDescription;
			}
			set
			{
				if ((this._EmailTemplateDescription != value))
				{
					this.OnEmailTemplateDescriptionChanging(value);
					this.SendPropertyChanging();
					this._EmailTemplateDescription = value;
					this.SendPropertyChanged("EmailTemplateDescription");
					this.OnEmailTemplateDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateKey
		{
			get
			{
				return this._EmailTemplateKey;
			}
			set
			{
				if ((this._EmailTemplateKey != value))
				{
					this.OnEmailTemplateKeyChanging(value);
					this.SendPropertyChanging();
					this._EmailTemplateKey = value;
					this.SendPropertyChanged("EmailTemplateKey");
					this.OnEmailTemplateKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFrom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this.OnEmailFromChanging(value);
					this.SendPropertyChanging();
					this._EmailFrom = value;
					this.SendPropertyChanged("EmailFrom");
					this.OnEmailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this.OnEmailSubjectChanging(value);
					this.SendPropertyChanging();
					this._EmailSubject = value;
					this.SendPropertyChanged("EmailSubject");
					this.OnEmailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this.OnEmailBodyChanging(value);
					this.SendPropertyChanging();
					this._EmailBody = value;
					this.SendPropertyChanged("EmailBody");
					this.OnEmailBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variables", DbType="VarChar(MAX)")]
		public string Variables
		{
			get
			{
				return this._Variables;
			}
			set
			{
				if ((this._Variables != value))
				{
					this.OnVariablesChanging(value);
					this.SendPropertyChanging();
					this._Variables = value;
					this.SendPropertyChanged("Variables");
					this.OnVariablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHTML", DbType="Bit NOT NULL")]
		public bool IsHTML
		{
			get
			{
				return this._IsHTML;
			}
			set
			{
				if ((this._IsHTML != value))
				{
					this.OnIsHTMLChanging(value);
					this.SendPropertyChanging();
					this._IsHTML = value;
					this.SendPropertyChanged("IsHTML");
					this.OnIsHTMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToVariable", DbType="VarChar(MAX)")]
		public string ToVariable
		{
			get
			{
				return this._ToVariable;
			}
			set
			{
				if ((this._ToVariable != value))
				{
					this.OnToVariableChanging(value);
					this.SendPropertyChanging();
					this._ToVariable = value;
					this.SendPropertyChanged("ToVariable");
					this.OnToVariableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CcVariable", DbType="VarChar(MAX)")]
		public string CcVariable
		{
			get
			{
				return this._CcVariable;
			}
			set
			{
				if ((this._CcVariable != value))
				{
					this.OnCcVariableChanging(value);
					this.SendPropertyChanging();
					this._CcVariable = value;
					this.SendPropertyChanged("CcVariable");
					this.OnCcVariableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasVariables", DbType="Bit NOT NULL")]
		public bool HasVariables
		{
			get
			{
				return this._HasVariables;
			}
			set
			{
				if ((this._HasVariables != value))
				{
					this.OnHasVariablesChanging(value);
					this.SendPropertyChanging();
					this._HasVariables = value;
					this.SendPropertyChanged("HasVariables");
					this.OnHasVariablesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendAsOneEmail", DbType="Bit")]
		public System.Nullable<bool> SendAsOneEmail
		{
			get
			{
				return this._SendAsOneEmail;
			}
			set
			{
				if ((this._SendAsOneEmail != value))
				{
					this.OnSendAsOneEmailChanging(value);
					this.SendPropertyChanging();
					this._SendAsOneEmail = value;
					this.SendPropertyChanged("SendAsOneEmail");
					this.OnSendAsOneEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class pr_INSERT_EmailQueueResult
	{
		
		private System.Nullable<int> _Column1;
		
		public pr_INSERT_EmailQueueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class pr_SELECT_ApplicationByKeyResult
	{
		
		private int _ApplicationID;
		
		private string _ApplicationKey;
		
		private string _ApplicationName;
		
		private string _ApplicationDescription;
		
		private string _ApplicationURL;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
		public pr_SELECT_ApplicationByKeyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int NOT NULL")]
		public int ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this._ApplicationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationKey
		{
			get
			{
				return this._ApplicationKey;
			}
			set
			{
				if ((this._ApplicationKey != value))
				{
					this._ApplicationKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this._ApplicationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationDescription", DbType="VarChar(250)")]
		public string ApplicationDescription
		{
			get
			{
				return this._ApplicationDescription;
			}
			set
			{
				if ((this._ApplicationDescription != value))
				{
					this._ApplicationDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationURL", DbType="VarChar(250)")]
		public string ApplicationURL
		{
			get
			{
				return this._ApplicationURL;
			}
			set
			{
				if ((this._ApplicationURL != value))
				{
					this._ApplicationURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class pr_SELECT_EmailAccountResult
	{
		
		private int _EmailAccountId;
		
		private int _ApplicationId;
		
		private string _EmailAccountDescription;
		
		private string _EmailAddress;
		
		private string _Username;
		
		private string _Password;
		
		private string _ServiceUrl;
		
		private int _PasswordExpiredDays;
		
		private System.DateTime _PasswordExpiredDate;
		
		private bool _PasswordNeverExpires;
		
		private bool _DeleteServerEmail;
		
		private bool _CanRecieve;
		
		private bool _CanSend;
		
		private bool _CheckUndeliverable;
		
		private int _AccountFailureCount;
		
		private int _MaxFailureCount;
		
		private bool _DisableAccount;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
		private bool _IsLocked;
		
		public pr_SELECT_EmailAccountResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAccountId", DbType="Int NOT NULL")]
		public int EmailAccountId
		{
			get
			{
				return this._EmailAccountId;
			}
			set
			{
				if ((this._EmailAccountId != value))
				{
					this._EmailAccountId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="Int NOT NULL")]
		public int ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this._ApplicationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAccountDescription", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string EmailAccountDescription
		{
			get
			{
				return this._EmailAccountDescription;
			}
			set
			{
				if ((this._EmailAccountDescription != value))
				{
					this._EmailAccountDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceUrl", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string ServiceUrl
		{
			get
			{
				return this._ServiceUrl;
			}
			set
			{
				if ((this._ServiceUrl != value))
				{
					this._ServiceUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordExpiredDays", DbType="Int NOT NULL")]
		public int PasswordExpiredDays
		{
			get
			{
				return this._PasswordExpiredDays;
			}
			set
			{
				if ((this._PasswordExpiredDays != value))
				{
					this._PasswordExpiredDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordExpiredDate", DbType="DateTime NOT NULL")]
		public System.DateTime PasswordExpiredDate
		{
			get
			{
				return this._PasswordExpiredDate;
			}
			set
			{
				if ((this._PasswordExpiredDate != value))
				{
					this._PasswordExpiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordNeverExpires", DbType="Bit NOT NULL")]
		public bool PasswordNeverExpires
		{
			get
			{
				return this._PasswordNeverExpires;
			}
			set
			{
				if ((this._PasswordNeverExpires != value))
				{
					this._PasswordNeverExpires = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteServerEmail", DbType="Bit NOT NULL")]
		public bool DeleteServerEmail
		{
			get
			{
				return this._DeleteServerEmail;
			}
			set
			{
				if ((this._DeleteServerEmail != value))
				{
					this._DeleteServerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanRecieve", DbType="Bit NOT NULL")]
		public bool CanRecieve
		{
			get
			{
				return this._CanRecieve;
			}
			set
			{
				if ((this._CanRecieve != value))
				{
					this._CanRecieve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanSend", DbType="Bit NOT NULL")]
		public bool CanSend
		{
			get
			{
				return this._CanSend;
			}
			set
			{
				if ((this._CanSend != value))
				{
					this._CanSend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckUndeliverable", DbType="Bit NOT NULL")]
		public bool CheckUndeliverable
		{
			get
			{
				return this._CheckUndeliverable;
			}
			set
			{
				if ((this._CheckUndeliverable != value))
				{
					this._CheckUndeliverable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountFailureCount", DbType="Int NOT NULL")]
		public int AccountFailureCount
		{
			get
			{
				return this._AccountFailureCount;
			}
			set
			{
				if ((this._AccountFailureCount != value))
				{
					this._AccountFailureCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxFailureCount", DbType="Int NOT NULL")]
		public int MaxFailureCount
		{
			get
			{
				return this._MaxFailureCount;
			}
			set
			{
				if ((this._MaxFailureCount != value))
				{
					this._MaxFailureCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisableAccount", DbType="Bit NOT NULL")]
		public bool DisableAccount
		{
			get
			{
				return this._DisableAccount;
			}
			set
			{
				if ((this._DisableAccount != value))
				{
					this._DisableAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this._IsLocked = value;
				}
			}
		}
	}
	
	public partial class pr_SELECT_EmailTemplatesResult
	{
		
		private int _EmailTemplateID;
		
		private int _ApplicationID;
		
		private string _EmailTemplateName;
		
		private string _EmailTemplateDescription;
		
		private string _EmailTemplateKey;
		
		private string _EmailFrom;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _Variables;
		
		private bool _IsHTML;
		
		private string _ToVariable;
		
		private string _CcVariable;
		
		private bool _HasVariables;
		
		private System.Nullable<bool> _SendAsOneEmail;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
		public pr_SELECT_EmailTemplatesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateID", DbType="Int NOT NULL")]
		public int EmailTemplateID
		{
			get
			{
				return this._EmailTemplateID;
			}
			set
			{
				if ((this._EmailTemplateID != value))
				{
					this._EmailTemplateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int NOT NULL")]
		public int ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this._ApplicationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateName
		{
			get
			{
				return this._EmailTemplateName;
			}
			set
			{
				if ((this._EmailTemplateName != value))
				{
					this._EmailTemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateDescription", DbType="VarChar(50)")]
		public string EmailTemplateDescription
		{
			get
			{
				return this._EmailTemplateDescription;
			}
			set
			{
				if ((this._EmailTemplateDescription != value))
				{
					this._EmailTemplateDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateKey
		{
			get
			{
				return this._EmailTemplateKey;
			}
			set
			{
				if ((this._EmailTemplateKey != value))
				{
					this._EmailTemplateKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFrom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this._EmailFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this._EmailBody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variables", DbType="VarChar(MAX)")]
		public string Variables
		{
			get
			{
				return this._Variables;
			}
			set
			{
				if ((this._Variables != value))
				{
					this._Variables = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHTML", DbType="Bit NOT NULL")]
		public bool IsHTML
		{
			get
			{
				return this._IsHTML;
			}
			set
			{
				if ((this._IsHTML != value))
				{
					this._IsHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToVariable", DbType="VarChar(MAX)")]
		public string ToVariable
		{
			get
			{
				return this._ToVariable;
			}
			set
			{
				if ((this._ToVariable != value))
				{
					this._ToVariable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CcVariable", DbType="VarChar(MAX)")]
		public string CcVariable
		{
			get
			{
				return this._CcVariable;
			}
			set
			{
				if ((this._CcVariable != value))
				{
					this._CcVariable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasVariables", DbType="Bit NOT NULL")]
		public bool HasVariables
		{
			get
			{
				return this._HasVariables;
			}
			set
			{
				if ((this._HasVariables != value))
				{
					this._HasVariables = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendAsOneEmail", DbType="Bit")]
		public System.Nullable<bool> SendAsOneEmail
		{
			get
			{
				return this._SendAsOneEmail;
			}
			set
			{
				if ((this._SendAsOneEmail != value))
				{
					this._SendAsOneEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	public partial class pr_SELECT_EmailTemplatesByApplicationResult
	{
		
		private int _EmailTemplateID;
		
		private int _ApplicationID;
		
		private string _EmailTemplateName;
		
		private string _EmailTemplateDescription;
		
		private string _EmailTemplateKey;
		
		private string _EmailFrom;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _Variables;
		
		private bool _IsHTML;
		
		private string _ToVariable;
		
		private string _CcVariable;
		
		private bool _HasVariables;
		
		private System.Nullable<bool> _SendAsOneEmail;
		
		private bool _IsActive;
		
		private bool _IsDeleted;
		
		public pr_SELECT_EmailTemplatesByApplicationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateID", DbType="Int NOT NULL")]
		public int EmailTemplateID
		{
			get
			{
				return this._EmailTemplateID;
			}
			set
			{
				if ((this._EmailTemplateID != value))
				{
					this._EmailTemplateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationID", DbType="Int NOT NULL")]
		public int ApplicationID
		{
			get
			{
				return this._ApplicationID;
			}
			set
			{
				if ((this._ApplicationID != value))
				{
					this._ApplicationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateName
		{
			get
			{
				return this._EmailTemplateName;
			}
			set
			{
				if ((this._EmailTemplateName != value))
				{
					this._EmailTemplateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateDescription", DbType="VarChar(50)")]
		public string EmailTemplateDescription
		{
			get
			{
				return this._EmailTemplateDescription;
			}
			set
			{
				if ((this._EmailTemplateDescription != value))
				{
					this._EmailTemplateDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTemplateKey", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailTemplateKey
		{
			get
			{
				return this._EmailTemplateKey;
			}
			set
			{
				if ((this._EmailTemplateKey != value))
				{
					this._EmailTemplateKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFrom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailFrom
		{
			get
			{
				return this._EmailFrom;
			}
			set
			{
				if ((this._EmailFrom != value))
				{
					this._EmailFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this._EmailBody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variables", DbType="VarChar(MAX)")]
		public string Variables
		{
			get
			{
				return this._Variables;
			}
			set
			{
				if ((this._Variables != value))
				{
					this._Variables = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHTML", DbType="Bit NOT NULL")]
		public bool IsHTML
		{
			get
			{
				return this._IsHTML;
			}
			set
			{
				if ((this._IsHTML != value))
				{
					this._IsHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToVariable", DbType="VarChar(MAX)")]
		public string ToVariable
		{
			get
			{
				return this._ToVariable;
			}
			set
			{
				if ((this._ToVariable != value))
				{
					this._ToVariable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CcVariable", DbType="VarChar(MAX)")]
		public string CcVariable
		{
			get
			{
				return this._CcVariable;
			}
			set
			{
				if ((this._CcVariable != value))
				{
					this._CcVariable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasVariables", DbType="Bit NOT NULL")]
		public bool HasVariables
		{
			get
			{
				return this._HasVariables;
			}
			set
			{
				if ((this._HasVariables != value))
				{
					this._HasVariables = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendAsOneEmail", DbType="Bit")]
		public System.Nullable<bool> SendAsOneEmail
		{
			get
			{
				return this._SendAsOneEmail;
			}
			set
			{
				if ((this._SendAsOneEmail != value))
				{
					this._SendAsOneEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
