//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommonCore_GoLiveEntities : DbContext
    {
        public CommonCore_GoLiveEntities()
            : base("name=CommonCore_GoLiveEntities")
        {
        }

        
        protected void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Actions> tb_Actions { get; set; }
        public DbSet<tb_ActiveDirectory> tb_ActiveDirectory { get; set; }
        public DbSet<tb_Applications> tb_Applications { get; set; }
        public DbSet<tb_AppSettings> tb_AppSettings { get; set; }
        public DbSet<tb_AuthenticationTypes> tb_AuthenticationTypes { get; set; }
        public DbSet<tb_BatchJobs> tb_BatchJobs { get; set; }
        public DbSet<tb_Delegations> tb_Delegations { get; set; }
        public DbSet<tb_EmailAccounts> tb_EmailAccounts { get; set; }
        public DbSet<tb_EmailAttachmentQueue> tb_EmailAttachmentQueue { get; set; }
        public DbSet<tb_EmailAttachmentQueueProcessed> tb_EmailAttachmentQueueProcessed { get; set; }
        public DbSet<tb_EmailExceptions> tb_EmailExceptions { get; set; }
        public DbSet<tb_EmailExceptionTypes> tb_EmailExceptionTypes { get; set; }
        public DbSet<tb_EmailLogs> tb_EmailLogs { get; set; }
        public DbSet<tb_EmailQueue> tb_EmailQueue { get; set; }
        public DbSet<tb_EmailQueueProcessed> tb_EmailQueueProcessed { get; set; }
        public DbSet<tb_EmailStaticAttachments> tb_EmailStaticAttachments { get; set; }
        public DbSet<tb_EmailTemplates> tb_EmailTemplates { get; set; }
        public DbSet<tb_Entities> tb_Entities { get; set; }
        public DbSet<tb_EntityActions> tb_EntityActions { get; set; }
        public DbSet<tb_EventLogs> tb_EventLogs { get; set; }
        public DbSet<tb_ReadEmailAttachments> tb_ReadEmailAttachments { get; set; }
        public DbSet<tb_ReadEmailItems> tb_ReadEmailItems { get; set; }
        public DbSet<tb_RecurringTypes> tb_RecurringTypes { get; set; }
        public DbSet<tb_ReferenceTypes> tb_ReferenceTypes { get; set; }
        public DbSet<tb_RoleActions> tb_RoleActions { get; set; }
        public DbSet<tb_RoleEntityActions> tb_RoleEntityActions { get; set; }
        public DbSet<tb_Roles> tb_Roles { get; set; }
        public DbSet<tb_Schedules> tb_Schedules { get; set; }
        public DbSet<tb_ScheduleTypes> tb_ScheduleTypes { get; set; }
        public DbSet<tb_Scripts> tb_Scripts { get; set; }
        public DbSet<tb_ScriptTypes> tb_ScriptTypes { get; set; }
        public DbSet<tb_UnreadEmailAttachments> tb_UnreadEmailAttachments { get; set; }
        public DbSet<tb_UnreadEmailItems> tb_UnreadEmailItems { get; set; }
        public DbSet<tb_UserApplications> tb_UserApplications { get; set; }
        public DbSet<tb_UserDetails> tb_UserDetails { get; set; }
        public DbSet<tb_userdetails_270513> tb_userdetails_270513 { get; set; }
        public DbSet<tb_UserDetails04072013> tb_UserDetails04072013 { get; set; }
        public DbSet<tb_UserDetails20130512> tb_UserDetails20130512 { get; set; }
        public DbSet<tb_UserDetails20141008> tb_UserDetails20141008 { get; set; }
        public DbSet<tb_UserLogInDetails> tb_UserLogInDetails { get; set; }
        public DbSet<tb_UserRoles> tb_UserRoles { get; set; }
        public DbSet<tb_Users> tb_Users { get; set; }
        public DbSet<tb_Users1> tb_Users1 { get; set; }
        public DbSet<tb_UserSubscriptions> tb_UserSubscriptions { get; set; }
        public DbSet<tb_Variables> tb_Variables { get; set; }
    }
}
