//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Applications
    {
        public int ApplicationID { get; set; }
        public string ApplicationKey { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationDescription { get; set; }
        public string ApplicationURL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
