//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailTemplates
    {
        public int EmailTemplateID { get; set; }
        public int ApplicationID { get; set; }
        public string EmailTemplateName { get; set; }
        public string EmailTemplateDescription { get; set; }
        public string EmailTemplateKey { get; set; }
        public string EmailFrom { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string Variables { get; set; }
        public bool IsHTML { get; set; }
        public string ToVariable { get; set; }
        public string CcVariable { get; set; }
        public bool HasVariables { get; set; }
        public Nullable<bool> SendAsOneEmail { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
