//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailStaticAttachments
    {
        public int EmailStaticAttachmentId { get; set; }
        public int EmailAccountId { get; set; }
        public int ApplicationId { get; set; }
        public string Filename { get; set; }
        public string ContentType { get; set; }
        public byte[] Attachment { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
