//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailAccounts
    {
        public int EmailAccountId { get; set; }
        public int ApplicationId { get; set; }
        public string EmailAccountDescription { get; set; }
        public string EmailAddress { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ServiceUrl { get; set; }
        public int PasswordExpiredDays { get; set; }
        public System.DateTime PasswordExpiredDate { get; set; }
        public bool PasswordNeverExpires { get; set; }
        public bool DeleteServerEmail { get; set; }
        public bool CanRecieve { get; set; }
        public bool CanSend { get; set; }
        public bool CheckUndeliverable { get; set; }
        public int AccountFailureCount { get; set; }
        public int MaxFailureCount { get; set; }
        public bool DisableAccount { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsLocked { get; set; }
    }
}
