//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserLogInDetails
    {
        public int UserLogInDetailsID { get; set; }
        public int UserID { get; set; }
        public int ApplicationID { get; set; }
        public System.DateTime LogInDateTime { get; set; }
        public string IPAddress { get; set; }
        public string ComputerName { get; set; }
        public Nullable<bool> LogInSuccessful { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> AuthenticationTypeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
