//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserDetails04072013
    {
        public int UserDetailsID { get; set; }
        public int UserID { get; set; }
        public string ServiceNumber { get; set; }
        public Nullable<int> ManagerUserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string PostalAddress1 { get; set; }
        public string PostalAddress2 { get; set; }
        public string PostalAddress3 { get; set; }
        public string PostalAddress4 { get; set; }
        public string PostalCode { get; set; }
        public string PhysicalAddress1 { get; set; }
        public string PhysicalAddress2 { get; set; }
        public string PhysicalAddress3 { get; set; }
        public string PhysicalAddress4 { get; set; }
        public string PhysicalCode { get; set; }
        public string TelephoneHome { get; set; }
        public string TelephoneWork { get; set; }
        public string Cellphone { get; set; }
        public string Designation { get; set; }
        public string BusinessUnit { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
