//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Exchange.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_SERVER;Initial Catalog=YOUR_DATABASE;Persist Security Info=Tr" +
            "ue;User ID=YOUR_USER;MultipleActiveResultSets=True")]
        public string CommonCore_GoLiveConnectionString1 {
            get {
                return ((string)(this["CommonCore_GoLiveConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_SERVER;Initial Catalog=YOUR_DATABASE;Persist Security Info=Tr" +
            "ue;User ID=YOUR_USER;MultipleActiveResultSets=True")]
        public string CommonCore_GoLiveConnectionString2 {
            get {
                return ((string)(this["CommonCore_GoLiveConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_SERVER;Initial Catalog=YOUR_DATABASE;Persist Security Info=Tr" +
            "ue;User ID=YOUR_USER;MultipleActiveResultSets=True")]
        public string CommonCore_GoLiveConnectionString {
            get {
                return ((string)(this["CommonCore_GoLiveConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=YOUR_SERVER;Initial Catalog=YOUR_DATABASE;Persist Security Info=Tr" +
            "ue;User ID=YOUR_USER;Password=YOUR_PASSWORD;MultipleActiveResultSets=True")]
        public string CommonCore_GoLiveConnectionString3 {
            get {
                return ((string)(this["CommonCore_GoLiveConnectionString3"]));
            }
        }
    }
}
