//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.TradeLicense.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_DA_GIS_DATA
    {
        public Nullable<double> OBJECTID { get; set; }
        public string REM { get; set; }
        public string PORTION { get; set; }
        public string ERF { get; set; }
        public string FARMTOWNNA { get; set; }
        public string STRNUM { get; set; }
        public string STRNAME { get; set; }
        public string STRTYPE { get; set; }
        public string SUBURB { get; set; }
        public string DISTRICT { get; set; }
        public string CITY { get; set; }
        public string WARDNO { get; set; }
        public string PostalCode { get; set; }
        public int ID { get; set; }
    }
}
