#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using C8.TradeLicense;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_EmailTamplatePartial.cshtml")]
    public partial class _Views_Shared__EmailTamplatePartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__EmailTamplatePartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"table-hover\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"font-family: Arial; font-size: 10pt\"");

WriteLiteral(">\r\n        Dear <b>{UserName}</b>,<br />\r\n        <br />\r\n        {Body}\r\n       " +
" <br />\r\n        <br />\r\n        <a");

WriteLiteral(" href=\"http://10.10.9.71:8085/\"");

WriteLiteral(">Click to login.</a>\r\n        <br/><br/>\r\n        Regards,<br />\r\n        <b>TLS " +
"Administrator</b>\r\n        <br/><hr/><br/>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
