//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Delegations
    {
        public int DelegationID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public int DelegateeUserID { get; set; }
        public int DelegatorUserID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
