//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailLogs
    {
        public int EmailLogID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<int> EmailTemplateID { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public int SentByUserID { get; set; }
    }
}
