//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ReadEmailAttachments
    {
        public int EmailAttachmentId { get; set; }
        public int EmailItemId { get; set; }
        public string Filename { get; set; }
        public string ContentType { get; set; }
        public byte[] Attachment { get; set; }
    }
}
