//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ReferenceTypes
    {
        public int ReferenceTypeId { get; set; }
        public string ReferenceTypeName { get; set; }
        public string ReferenceTypeDescription { get; set; }
        public string ReferenceTypeKey { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsLocked { get; set; }
    }
}
