//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UnreadEmailItems
    {
        public int EmailItemId { get; set; }
        public int EmailAccountId { get; set; }
        public int ApplicationId { get; set; }
        public string FromList { get; set; }
        public string ToList { get; set; }
        public string CcList { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime RecievedDateTime { get; set; }
        public Nullable<bool> IsHtml { get; set; }
        public bool IsProcessed { get; set; }
        public bool HasAttachments { get; set; }
    }
}
