//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.Windows.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Variables
    {
        public int VariableID { get; set; }
        public string VariableName { get; set; }
        public string SQLStatement { get; set; }
        public string VariableKey { get; set; }
        public string ServerName { get; set; }
        public string ServerPort { get; set; }
        public string DatabaseName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int ApplicationID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
