//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C8.TradeLicense.GIS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
    public partial class Error_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errortCodeField;
        
        private string errorMSGField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrortCode {
            get {
                return this.errortCodeField;
            }
            set {
                this.errortCodeField = value;
                this.RaisePropertyChanged("ErrortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMSG {
            get {
                return this.errorMSGField;
            }
            set {
                this.errorMSGField = value;
                this.RaisePropertyChanged("ErrorMSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
    public partial class GISResponseDetails_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gISIdField;
        
        private string erfField;
        
        private string portionField;
        
        private string farmTownshipField;
        
        private string remainderField;
        
        private string unitNumberField;
        
        private string floorNumberField;
        
        private string sectionNumberField;
        
        private string buildingComplexField;
        
        private string streetNumberField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string suburbField;
        
        private string cityField;
        
        private string codeField;
        
        private string streetAddressLongitudeField;
        
        private string streetAddressLatitudeField;
        
        private string councillorField;
        
        private string wardRepresentativeField;
        
        private string wardNumberField;
        
        private string pinIdField;
        
        private string rateNumberField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GISId {
            get {
                return this.gISIdField;
            }
            set {
                this.gISIdField = value;
                this.RaisePropertyChanged("GISId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Erf {
            get {
                return this.erfField;
            }
            set {
                this.erfField = value;
                this.RaisePropertyChanged("Erf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
                this.RaisePropertyChanged("Portion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FarmTownship {
            get {
                return this.farmTownshipField;
            }
            set {
                this.farmTownshipField = value;
                this.RaisePropertyChanged("FarmTownship");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Remainder {
            get {
                return this.remainderField;
            }
            set {
                this.remainderField = value;
                this.RaisePropertyChanged("Remainder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UnitNumber {
            get {
                return this.unitNumberField;
            }
            set {
                this.unitNumberField = value;
                this.RaisePropertyChanged("UnitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FloorNumber {
            get {
                return this.floorNumberField;
            }
            set {
                this.floorNumberField = value;
                this.RaisePropertyChanged("FloorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SectionNumber {
            get {
                return this.sectionNumberField;
            }
            set {
                this.sectionNumberField = value;
                this.RaisePropertyChanged("SectionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string BuildingComplex {
            get {
                return this.buildingComplexField;
            }
            set {
                this.buildingComplexField = value;
                this.RaisePropertyChanged("BuildingComplex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
                this.RaisePropertyChanged("Suburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string StreetAddressLongitude {
            get {
                return this.streetAddressLongitudeField;
            }
            set {
                this.streetAddressLongitudeField = value;
                this.RaisePropertyChanged("StreetAddressLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string StreetAddressLatitude {
            get {
                return this.streetAddressLatitudeField;
            }
            set {
                this.streetAddressLatitudeField = value;
                this.RaisePropertyChanged("StreetAddressLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Councillor {
            get {
                return this.councillorField;
            }
            set {
                this.councillorField = value;
                this.RaisePropertyChanged("Councillor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WardRepresentative {
            get {
                return this.wardRepresentativeField;
            }
            set {
                this.wardRepresentativeField = value;
                this.RaisePropertyChanged("WardRepresentative");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string WardNumber {
            get {
                return this.wardNumberField;
            }
            set {
                this.wardNumberField = value;
                this.RaisePropertyChanged("WardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PinId {
            get {
                return this.pinIdField;
            }
            set {
                this.pinIdField = value;
                this.RaisePropertyChanged("PinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string RateNumber {
            get {
                return this.rateNumberField;
            }
            set {
                this.rateNumberField = value;
                this.RaisePropertyChanged("RateNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
    public partial class Status_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusMSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMSG {
            get {
                return this.statusMSGField;
            }
            set {
                this.statusMSGField = value;
                this.RaisePropertyChanged("StatusMSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
    public partial class GISResponse_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status_T statusField;
        
        private GISResponseDetails_T[] gISResponseDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status_T Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GISResponseDetails", Order=1)]
        public GISResponseDetails_T[] GISResponseDetails {
            get {
                return this.gISResponseDetailsField;
            }
            set {
                this.gISResponseDetailsField = value;
                this.RaisePropertyChanged("GISResponseDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
    public partial class GIS_Request_T : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string streetNumberField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string accountNumberField;
        
        private string erfField;
        
        private string portionField;
        
        private string farmTownshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("StreetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
                this.RaisePropertyChanged("StreetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Erf {
            get {
                return this.erfField;
            }
            set {
                this.erfField = value;
                this.RaisePropertyChanged("Erf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Portion {
            get {
                return this.portionField;
            }
            set {
                this.portionField = value;
                this.RaisePropertyChanged("Portion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FarmTownship {
            get {
                return this.farmTownshipField;
            }
            set {
                this.farmTownshipField = value;
                this.RaisePropertyChanged("FarmTownship");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1471170409795", ConfigurationName="GIS.PortType")]
    public interface PortType {
        
        // CODEGEN: Generating message contract since the operation Operation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="/Services/GIS_Abstract_WSDL-service0.serviceagent/PortTypeEndpoint0/Operation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(C8.TradeLicense.GIS.Error_T), Action="/Services/GIS_Abstract_WSDL-service0.serviceagent/PortTypeEndpoint0/Operation", Name="Error", Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        C8.TradeLicense.GIS.OperationResponse Operation(C8.TradeLicense.GIS.OperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/Services/GIS_Abstract_WSDL-service0.serviceagent/PortTypeEndpoint0/Operation", ReplyAction="*")]
        System.Threading.Tasks.Task<C8.TradeLicense.GIS.OperationResponse> OperationAsync(C8.TradeLicense.GIS.OperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd", Order=0)]
        public C8.TradeLicense.GIS.GIS_Request_T GIS_Request;
        
        public OperationRequest() {
        }
        
        public OperationRequest(C8.TradeLicense.GIS.GIS_Request_T GIS_Request) {
            this.GIS_Request = GIS_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tibco.com/schemas/ESB_GIS_Service/SharedResources/Schema/Schema.xsd", Order=0)]
        public C8.TradeLicense.GIS.GISResponse_T GISResponse;
        
        public OperationResponse() {
        }
        
        public OperationResponse(C8.TradeLicense.GIS.GISResponse_T GISResponse) {
            this.GISResponse = GISResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortTypeChannel : C8.TradeLicense.GIS.PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortTypeClient : System.ServiceModel.ClientBase<C8.TradeLicense.GIS.PortType>, C8.TradeLicense.GIS.PortType {
        
        public PortTypeClient() {
        }
        
        public PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C8.TradeLicense.GIS.OperationResponse C8.TradeLicense.GIS.PortType.Operation(C8.TradeLicense.GIS.OperationRequest request) {
            return base.Channel.Operation(request);
        }
        
        public C8.TradeLicense.GIS.GISResponse_T Operation(C8.TradeLicense.GIS.GIS_Request_T GIS_Request) {
            C8.TradeLicense.GIS.OperationRequest inValue = new C8.TradeLicense.GIS.OperationRequest();
            inValue.GIS_Request = GIS_Request;
            C8.TradeLicense.GIS.OperationResponse retVal = ((C8.TradeLicense.GIS.PortType)(this)).Operation(inValue);
            return retVal.GISResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<C8.TradeLicense.GIS.OperationResponse> C8.TradeLicense.GIS.PortType.OperationAsync(C8.TradeLicense.GIS.OperationRequest request) {
            return base.Channel.OperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<C8.TradeLicense.GIS.OperationResponse> OperationAsync(C8.TradeLicense.GIS.GIS_Request_T GIS_Request) {
            C8.TradeLicense.GIS.OperationRequest inValue = new C8.TradeLicense.GIS.OperationRequest();
            inValue.GIS_Request = GIS_Request;
            return ((C8.TradeLicense.GIS.PortType)(this)).OperationAsync(inValue);
        }
    }
}
