use TradeLicenseSystem

delete from[dbo].[__MigrationHistory]
delete from[dbo].[_LicenseCondition]
delete from[dbo].[_LicensesCentral]
delete from[dbo].[_LicenseSubType]
delete from[dbo].[_StreetNames]

delete from[dbo].[cmn_sequences]
delete from[dbo].[Refusals]
delete from[dbo].[FileUploads]
delete from[dbo].[AdministratorReviews]
delete from[dbo].[ManagerReviews]
delete from[dbo].[Payments]
delete from[dbo].[ELMAH_Error]
delete from[dbo].[RevokeCancelReviews]
delete from[dbo].[InspectionHistories]
delete from[dbo].[InspectionAppealsReviews]
delete from[dbo].[InspectionAppeals]
delete from[dbo].[InspectionResponses]
delete from[dbo].[InspectionRequests]

delete from[dbo].[Licenses]
delete from[dbo].[Amendments]
delete from[dbo].[ChiefReviews]
delete from[dbo].[RevokeCancelReviews]
delete from[dbo].[EscalationMainTables]
delete from[dbo].[BusinessEmployees]
delete from[dbo].[BusinessMangers]

delete from[dbo].[BusinessOperators]
delete from[dbo].[BusinessOperationTypes]
delete from[dbo].[BusinessTypes]

delete from[dbo].[Businesses]
delete from[dbo].[Clients]

delete from[dbo].[ChiefReviews]
delete from[dbo].[PaymentLicenses]
delete from[dbo].[LicensesRevokeds]

delete from[dbo].[LicensesRevokeds]
delete from [dbo].[Audits]
delete from[dbo].[FileUploads]
delete from[dbo].[Documents]
delete from[dbo].[DocumentTypes]
delete from[dbo].[Conditions]
delete from[dbo].[DepartmentContacts]
delete from[dbo].[Departments]
delete from[dbo].[DepartmentServiceLevelAgreements]
delete from[dbo].[AspNetUsers]
delete from[dbo].[AspNetRoles]
delete from[dbo].[AspNetUserClaims]
delete from[dbo].[AspNetUserLogins]
delete from[dbo].[AspNetUserRoles]
delete from[dbo].[DropdownItems]
delete from[dbo].[ELMAH_Error]
delete from[dbo].[Enquiries]
delete from[dbo].[LookupTables]
delete from[dbo].[EscalationLogs]
delete from[dbo].[ItemConditions]
delete from[dbo].[ItemSubCategories]
delete from[dbo].[ItemTypes]
delete from[dbo].[LicenseApplicationConditions]
delete from[dbo].[NumOfDays]
delete from[dbo].[MigratedBusinesses]
delete from[dbo].[MigratedClients]
delete from[dbo].[MigratedLicenses]
delete from[dbo].[OperationStructureTypes]
delete from[dbo].[PublicHolidays]
delete from[dbo].[Regions]
delete from[dbo].[ServiceLevelAgreements]
delete from[dbo].[StatusTypes]
delete from[dbo].[Status]
delete from[dbo].[TitleDeedTypes]
delete from[dbo].[Users]
delete from[dbo].[ViewSettings]